source 'https://rubygems.org'

ruby '2.4.2'

gem 'rake'
gem 'sinatra'
gem 'sinatra-flash'
gem 'bcrypt'
gem 'warden'
gem 'shotgun'
gem 'json', '1.8.6'
gem 'data_mapper'
gem 'dm-core'
gem 'pg'
gem 'dm-postgres-adapter'
gem 'dm-migrations'
gem 'dm-serializer'
gem 'dm-timestamps'
gem 'dm-transactions'
gem 'dm-types'
gem 'dm-validations'
